/**
 * API documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ThingsPostRequest {
    /**
    * Set the name of the thing
    */
    'name': string;
    /**
    * One of cc, cc-sa, cc-nd, cc-nc-sa, cc-nc-nd, pd0, gpl, lgpl, bsd. Set license.
    */
    'license': string;
    /**
    * Set the category of the thing. Uses full category name (eg. \"3D Printer Parts\")
    */
    'category': string;
    /**
    * Set the description.
    */
    'description'?: string;
    /**
    * Set the instructions.
    */
    'instructions'?: string;
    /**
    * Toggle whether this thing is a work in progress. Default is false.
    */
    'isWip'?: boolean;
    /**
    * An array of strings containing tag names. Sets all current tags.
    */
    'tags'?: Array<string>;
    /**
    * An array of thing ids that this thing is derived from.
    */
    'ancestors'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "instructions",
            "baseName": "instructions",
            "type": "string"
        },
        {
            "name": "isWip",
            "baseName": "is_wip",
            "type": "boolean"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "ancestors",
            "baseName": "ancestors",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ThingsPostRequest.attributeTypeMap;
    }
}

