AppPathById:
  get:
    tags:
      - App
    summary: Get app by id
    security:
      - BearerAuth: []
    parameters:
      - in: path
        name: id
        required: true
        description: The id of the app to get
        schema:
          type: number
          example: 22
    responses:
      '200':
        description: An object representing the app requested
        content:
            application/json:
              schema:
                $ref: '../schemas/app_schema.yaml'
      '401':
        $ref : "../responses/unauthorized.yaml"
      '403':
        $ref : "../responses/forbidden.yaml"
      '404':
        $ref : "../responses/not_found.yaml"
